name: Project CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Clear Maven Cache
      run: mvn clean
      working-directory: ./backend/csm

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./backend/csm

    - name: Update dependency graph
      uses: ./backend/csm/advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
