name: Project CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Verify Repository Structure
      run: ls -R
      working-directory: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean install
      working-directory: backend/csm  # ✅ Running inside correct directory

    - name: Update dependency graph
      run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph
      working-directory: backend/csm  # ✅ Running inside correct directory
